// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// eigen_Xt_times_X_cpp
Eigen::MatrixXd eigen_Xt_times_X_cpp(SEXP X_sexp);
RcppExport SEXP _PTE_eigen_Xt_times_X_cpp(SEXP X_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_sexp(X_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(eigen_Xt_times_X_cpp(X_sexp));
    return rcpp_result_gen;
END_RCPP
}
// eigen_compute_single_entry_on_diagonal_of_inverse_matrix_cpp
double eigen_compute_single_entry_on_diagonal_of_inverse_matrix_cpp(SEXP M_sexp, int j);
RcppExport SEXP _PTE_eigen_compute_single_entry_on_diagonal_of_inverse_matrix_cpp(SEXP M_sexpSEXP, SEXP jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type M_sexp(M_sexpSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    rcpp_result_gen = Rcpp::wrap(eigen_compute_single_entry_on_diagonal_of_inverse_matrix_cpp(M_sexp, j));
    return rcpp_result_gen;
END_RCPP
}
// eigen_Xt_times_diag_w_times_X_cpp
Eigen::MatrixXd eigen_Xt_times_diag_w_times_X_cpp(SEXP X_sexp, SEXP w_sexp);
RcppExport SEXP _PTE_eigen_Xt_times_diag_w_times_X_cpp(SEXP X_sexpSEXP, SEXP w_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_sexp(X_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type w_sexp(w_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(eigen_Xt_times_diag_w_times_X_cpp(X_sexp, w_sexp));
    return rcpp_result_gen;
END_RCPP
}
// likelihood_ratio_test_from_negloglik_cpp
Rcpp::List likelihood_ratio_test_from_negloglik_cpp(double unrestricted_neg_loglik, double null_neg_loglik, int df);
RcppExport SEXP _PTE_likelihood_ratio_test_from_negloglik_cpp(SEXP unrestricted_neg_loglikSEXP, SEXP null_neg_loglikSEXP, SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type unrestricted_neg_loglik(unrestricted_neg_loglikSEXP);
    Rcpp::traits::input_parameter< double >::type null_neg_loglik(null_neg_loglikSEXP);
    Rcpp::traits::input_parameter< int >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(likelihood_ratio_test_from_negloglik_cpp(unrestricted_neg_loglik, null_neg_loglik, df));
    return rcpp_result_gen;
END_RCPP
}
// score_test_from_score_information_cpp
Rcpp::List score_test_from_score_information_cpp(SEXP score_sexp, SEXP information_sexp, int tested_idx);
RcppExport SEXP _PTE_score_test_from_score_information_cpp(SEXP score_sexpSEXP, SEXP information_sexpSEXP, SEXP tested_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type score_sexp(score_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type information_sexp(information_sexpSEXP);
    Rcpp::traits::input_parameter< int >::type tested_idx(tested_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(score_test_from_score_information_cpp(score_sexp, information_sexp, tested_idx));
    return rcpp_result_gen;
END_RCPP
}
// gradient_test_from_restricted_score_cpp
Rcpp::List gradient_test_from_restricted_score_cpp(SEXP score_sexp, double unrestricted_estimate, double null_value, int tested_idx);
RcppExport SEXP _PTE_gradient_test_from_restricted_score_cpp(SEXP score_sexpSEXP, SEXP unrestricted_estimateSEXP, SEXP null_valueSEXP, SEXP tested_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type score_sexp(score_sexpSEXP);
    Rcpp::traits::input_parameter< double >::type unrestricted_estimate(unrestricted_estimateSEXP);
    Rcpp::traits::input_parameter< double >::type null_value(null_valueSEXP);
    Rcpp::traits::input_parameter< int >::type tested_idx(tested_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(gradient_test_from_restricted_score_cpp(score_sexp, unrestricted_estimate, null_value, tested_idx));
    return rcpp_result_gen;
END_RCPP
}
// mean_cpp
double mean_cpp(SEXP x_sexp);
RcppExport SEXP _PTE_mean_cpp(SEXP x_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x_sexp(x_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(mean_cpp(x_sexp));
    return rcpp_result_gen;
END_RCPP
}
// var_cpp
double var_cpp(SEXP x_sexp);
RcppExport SEXP _PTE_var_cpp(SEXP x_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x_sexp(x_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(var_cpp(x_sexp));
    return rcpp_result_gen;
END_RCPP
}
// get_logistic_regression_score_cpp
Eigen::VectorXd get_logistic_regression_score_cpp(SEXP X_sexp, SEXP y_sexp, SEXP beta_sexp);
RcppExport SEXP _PTE_get_logistic_regression_score_cpp(SEXP X_sexpSEXP, SEXP y_sexpSEXP, SEXP beta_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_sexp(X_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y_sexp(y_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type beta_sexp(beta_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(get_logistic_regression_score_cpp(X_sexp, y_sexp, beta_sexp));
    return rcpp_result_gen;
END_RCPP
}
// get_logistic_regression_hessian_cpp
Eigen::MatrixXd get_logistic_regression_hessian_cpp(SEXP X_sexp, SEXP beta_sexp);
RcppExport SEXP _PTE_get_logistic_regression_hessian_cpp(SEXP X_sexpSEXP, SEXP beta_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_sexp(X_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type beta_sexp(beta_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(get_logistic_regression_hessian_cpp(X_sexp, beta_sexp));
    return rcpp_result_gen;
END_RCPP
}
// get_logistic_regression_weighted_score_cpp
Eigen::VectorXd get_logistic_regression_weighted_score_cpp(SEXP X_sexp, SEXP y_sexp, SEXP weights_sexp, SEXP beta_sexp);
RcppExport SEXP _PTE_get_logistic_regression_weighted_score_cpp(SEXP X_sexpSEXP, SEXP y_sexpSEXP, SEXP weights_sexpSEXP, SEXP beta_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_sexp(X_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y_sexp(y_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type weights_sexp(weights_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type beta_sexp(beta_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(get_logistic_regression_weighted_score_cpp(X_sexp, y_sexp, weights_sexp, beta_sexp));
    return rcpp_result_gen;
END_RCPP
}
// get_logistic_regression_weighted_hessian_cpp
Eigen::MatrixXd get_logistic_regression_weighted_hessian_cpp(SEXP X_sexp, SEXP weights_sexp, SEXP beta_sexp);
RcppExport SEXP _PTE_get_logistic_regression_weighted_hessian_cpp(SEXP X_sexpSEXP, SEXP weights_sexpSEXP, SEXP beta_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_sexp(X_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type weights_sexp(weights_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type beta_sexp(beta_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(get_logistic_regression_weighted_hessian_cpp(X_sexp, weights_sexp, beta_sexp));
    return rcpp_result_gen;
END_RCPP
}
// fast_logistic_regression_cpp
List fast_logistic_regression_cpp(SEXP X_sexp, SEXP y_sexp, Rcpp::Nullable<Rcpp::NumericVector> warm_start_beta, bool smart_cold_start, int maxit, double tol, Rcpp::Nullable<Rcpp::IntegerVector> fixed_idx, Rcpp::Nullable<Rcpp::NumericVector> fixed_values, std::string optimization_alg, Rcpp::Nullable<Rcpp::NumericVector> warm_start_weights, Rcpp::Nullable<Rcpp::NumericMatrix> warm_start_fisher_info, bool estimate_only);
RcppExport SEXP _PTE_fast_logistic_regression_cpp(SEXP X_sexpSEXP, SEXP y_sexpSEXP, SEXP warm_start_betaSEXP, SEXP smart_cold_startSEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP fixed_idxSEXP, SEXP fixed_valuesSEXP, SEXP optimization_algSEXP, SEXP warm_start_weightsSEXP, SEXP warm_start_fisher_infoSEXP, SEXP estimate_onlySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_sexp(X_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y_sexp(y_sexpSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type warm_start_beta(warm_start_betaSEXP);
    Rcpp::traits::input_parameter< bool >::type smart_cold_start(smart_cold_startSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type fixed_idx(fixed_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type fixed_values(fixed_valuesSEXP);
    Rcpp::traits::input_parameter< std::string >::type optimization_alg(optimization_algSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type warm_start_weights(warm_start_weightsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type warm_start_fisher_info(warm_start_fisher_infoSEXP);
    Rcpp::traits::input_parameter< bool >::type estimate_only(estimate_onlySEXP);
    rcpp_result_gen = Rcpp::wrap(fast_logistic_regression_cpp(X_sexp, y_sexp, warm_start_beta, smart_cold_start, maxit, tol, fixed_idx, fixed_values, optimization_alg, warm_start_weights, warm_start_fisher_info, estimate_only));
    return rcpp_result_gen;
END_RCPP
}
// fast_logistic_regression_weighted_cpp
List fast_logistic_regression_weighted_cpp(SEXP X_sexp, SEXP y_sexp, SEXP weights_sexp, Rcpp::Nullable<Rcpp::NumericVector> warm_start_beta, bool smart_cold_start, int maxit, double tol, Rcpp::Nullable<Rcpp::IntegerVector> fixed_idx, Rcpp::Nullable<Rcpp::NumericVector> fixed_values, std::string optimization_alg, Rcpp::Nullable<Rcpp::NumericVector> warm_start_weights, Rcpp::Nullable<Rcpp::NumericMatrix> warm_start_fisher_info);
RcppExport SEXP _PTE_fast_logistic_regression_weighted_cpp(SEXP X_sexpSEXP, SEXP y_sexpSEXP, SEXP weights_sexpSEXP, SEXP warm_start_betaSEXP, SEXP smart_cold_startSEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP fixed_idxSEXP, SEXP fixed_valuesSEXP, SEXP optimization_algSEXP, SEXP warm_start_weightsSEXP, SEXP warm_start_fisher_infoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_sexp(X_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y_sexp(y_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type weights_sexp(weights_sexpSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type warm_start_beta(warm_start_betaSEXP);
    Rcpp::traits::input_parameter< bool >::type smart_cold_start(smart_cold_startSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type fixed_idx(fixed_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type fixed_values(fixed_valuesSEXP);
    Rcpp::traits::input_parameter< std::string >::type optimization_alg(optimization_algSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type warm_start_weights(warm_start_weightsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type warm_start_fisher_info(warm_start_fisher_infoSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_logistic_regression_weighted_cpp(X_sexp, y_sexp, weights_sexp, warm_start_beta, smart_cold_start, maxit, tol, fixed_idx, fixed_values, optimization_alg, warm_start_weights, warm_start_fisher_info));
    return rcpp_result_gen;
END_RCPP
}
// fast_logistic_regression_with_var_cpp
List fast_logistic_regression_with_var_cpp(SEXP X_sexp, SEXP y_sexp, int j, Rcpp::Nullable<Rcpp::NumericVector> warm_start_beta, bool smart_cold_start, Rcpp::Nullable<Rcpp::IntegerVector> fixed_idx, Rcpp::Nullable<Rcpp::NumericVector> fixed_values, std::string optimization_alg, Rcpp::Nullable<Rcpp::NumericVector> warm_start_weights, Rcpp::Nullable<Rcpp::NumericMatrix> warm_start_fisher_info);
RcppExport SEXP _PTE_fast_logistic_regression_with_var_cpp(SEXP X_sexpSEXP, SEXP y_sexpSEXP, SEXP jSEXP, SEXP warm_start_betaSEXP, SEXP smart_cold_startSEXP, SEXP fixed_idxSEXP, SEXP fixed_valuesSEXP, SEXP optimization_algSEXP, SEXP warm_start_weightsSEXP, SEXP warm_start_fisher_infoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_sexp(X_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y_sexp(y_sexpSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type warm_start_beta(warm_start_betaSEXP);
    Rcpp::traits::input_parameter< bool >::type smart_cold_start(smart_cold_startSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type fixed_idx(fixed_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type fixed_values(fixed_valuesSEXP);
    Rcpp::traits::input_parameter< std::string >::type optimization_alg(optimization_algSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type warm_start_weights(warm_start_weightsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type warm_start_fisher_info(warm_start_fisher_infoSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_logistic_regression_with_var_cpp(X_sexp, y_sexp, j, warm_start_beta, smart_cold_start, fixed_idx, fixed_values, optimization_alg, warm_start_weights, warm_start_fisher_info));
    return rcpp_result_gen;
END_RCPP
}
// get_weibull_regression_score_cpp
Eigen::VectorXd get_weibull_regression_score_cpp(SEXP X_sexp, SEXP y_sexp, SEXP dead_sexp, SEXP params_sexp);
RcppExport SEXP _PTE_get_weibull_regression_score_cpp(SEXP X_sexpSEXP, SEXP y_sexpSEXP, SEXP dead_sexpSEXP, SEXP params_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_sexp(X_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y_sexp(y_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dead_sexp(dead_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type params_sexp(params_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(get_weibull_regression_score_cpp(X_sexp, y_sexp, dead_sexp, params_sexp));
    return rcpp_result_gen;
END_RCPP
}
// get_weibull_regression_hessian_cpp
Eigen::MatrixXd get_weibull_regression_hessian_cpp(SEXP X_sexp, SEXP y_sexp, SEXP dead_sexp, SEXP params_sexp);
RcppExport SEXP _PTE_get_weibull_regression_hessian_cpp(SEXP X_sexpSEXP, SEXP y_sexpSEXP, SEXP dead_sexpSEXP, SEXP params_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_sexp(X_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y_sexp(y_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dead_sexp(dead_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type params_sexp(params_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(get_weibull_regression_hessian_cpp(X_sexp, y_sexp, dead_sexp, params_sexp));
    return rcpp_result_gen;
END_RCPP
}
// compute_weibull_rand_bootstrap_parallel_cpp
NumericVector compute_weibull_rand_bootstrap_parallel_cpp(const NumericVector& y0, const IntegerVector& dead, const NumericMatrix& Xc, const IntegerMatrix& i_mat, const IntegerMatrix& w_mat, double delta, Rcpp::Nullable<Rcpp::NumericMatrix> noise_mat, int num_cores);
RcppExport SEXP _PTE_compute_weibull_rand_bootstrap_parallel_cpp(SEXP y0SEXP, SEXP deadSEXP, SEXP XcSEXP, SEXP i_matSEXP, SEXP w_matSEXP, SEXP deltaSEXP, SEXP noise_matSEXP, SEXP num_coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type y0(y0SEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type dead(deadSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Xc(XcSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type i_mat(i_matSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type w_mat(w_matSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type noise_mat(noise_matSEXP);
    Rcpp::traits::input_parameter< int >::type num_cores(num_coresSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_weibull_rand_bootstrap_parallel_cpp(y0, dead, Xc, i_mat, w_mat, delta, noise_mat, num_cores));
    return rcpp_result_gen;
END_RCPP
}
// fast_weibull_regression_cpp
List fast_weibull_regression_cpp(SEXP X_sexp, SEXP y_sexp, SEXP dead_sexp, Nullable<NumericVector> warm_start_params, bool smart_cold_start, bool estimate_only, int maxit, double tol, Rcpp::Nullable<Rcpp::IntegerVector> fixed_idx, Rcpp::Nullable<Rcpp::NumericVector> fixed_values, std::string optimization_alg, Rcpp::Nullable<Rcpp::NumericMatrix> warm_start_fisher_info);
RcppExport SEXP _PTE_fast_weibull_regression_cpp(SEXP X_sexpSEXP, SEXP y_sexpSEXP, SEXP dead_sexpSEXP, SEXP warm_start_paramsSEXP, SEXP smart_cold_startSEXP, SEXP estimate_onlySEXP, SEXP maxitSEXP, SEXP tolSEXP, SEXP fixed_idxSEXP, SEXP fixed_valuesSEXP, SEXP optimization_algSEXP, SEXP warm_start_fisher_infoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_sexp(X_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y_sexp(y_sexpSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dead_sexp(dead_sexpSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type warm_start_params(warm_start_paramsSEXP);
    Rcpp::traits::input_parameter< bool >::type smart_cold_start(smart_cold_startSEXP);
    Rcpp::traits::input_parameter< bool >::type estimate_only(estimate_onlySEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type fixed_idx(fixed_idxSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type fixed_values(fixed_valuesSEXP);
    Rcpp::traits::input_parameter< std::string >::type optimization_alg(optimization_algSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type warm_start_fisher_info(warm_start_fisher_infoSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_weibull_regression_cpp(X_sexp, y_sexp, dead_sexp, warm_start_params, smart_cold_start, estimate_only, maxit, tol, fixed_idx, fixed_values, optimization_alg, warm_start_fisher_info));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PTE_eigen_Xt_times_X_cpp", (DL_FUNC) &_PTE_eigen_Xt_times_X_cpp, 1},
    {"_PTE_eigen_compute_single_entry_on_diagonal_of_inverse_matrix_cpp", (DL_FUNC) &_PTE_eigen_compute_single_entry_on_diagonal_of_inverse_matrix_cpp, 2},
    {"_PTE_eigen_Xt_times_diag_w_times_X_cpp", (DL_FUNC) &_PTE_eigen_Xt_times_diag_w_times_X_cpp, 2},
    {"_PTE_likelihood_ratio_test_from_negloglik_cpp", (DL_FUNC) &_PTE_likelihood_ratio_test_from_negloglik_cpp, 3},
    {"_PTE_score_test_from_score_information_cpp", (DL_FUNC) &_PTE_score_test_from_score_information_cpp, 3},
    {"_PTE_gradient_test_from_restricted_score_cpp", (DL_FUNC) &_PTE_gradient_test_from_restricted_score_cpp, 4},
    {"_PTE_mean_cpp", (DL_FUNC) &_PTE_mean_cpp, 1},
    {"_PTE_var_cpp", (DL_FUNC) &_PTE_var_cpp, 1},
    {"_PTE_get_logistic_regression_score_cpp", (DL_FUNC) &_PTE_get_logistic_regression_score_cpp, 3},
    {"_PTE_get_logistic_regression_hessian_cpp", (DL_FUNC) &_PTE_get_logistic_regression_hessian_cpp, 2},
    {"_PTE_get_logistic_regression_weighted_score_cpp", (DL_FUNC) &_PTE_get_logistic_regression_weighted_score_cpp, 4},
    {"_PTE_get_logistic_regression_weighted_hessian_cpp", (DL_FUNC) &_PTE_get_logistic_regression_weighted_hessian_cpp, 3},
    {"_PTE_fast_logistic_regression_cpp", (DL_FUNC) &_PTE_fast_logistic_regression_cpp, 12},
    {"_PTE_fast_logistic_regression_weighted_cpp", (DL_FUNC) &_PTE_fast_logistic_regression_weighted_cpp, 12},
    {"_PTE_fast_logistic_regression_with_var_cpp", (DL_FUNC) &_PTE_fast_logistic_regression_with_var_cpp, 10},
    {"_PTE_get_weibull_regression_score_cpp", (DL_FUNC) &_PTE_get_weibull_regression_score_cpp, 4},
    {"_PTE_get_weibull_regression_hessian_cpp", (DL_FUNC) &_PTE_get_weibull_regression_hessian_cpp, 4},
    {"_PTE_compute_weibull_rand_bootstrap_parallel_cpp", (DL_FUNC) &_PTE_compute_weibull_rand_bootstrap_parallel_cpp, 8},
    {"_PTE_fast_weibull_regression_cpp", (DL_FUNC) &_PTE_fast_weibull_regression_cpp, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_PTE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
